### ISSUE TITLE
In DMX-Controls tab the range of channels invalid inputs not updating correctly

### ISSUE THREAD

**Issue by ethanpartida** [teslaworksumn/lightshow-Gallium#124]

**Comment by ethanpartida** [comment]
![incorrectError](https://user-images.githubusercontent.com/42383664/68057137-09845300-fcc3-11e9-8374-58eb321640f4.png)

**Comment by theeldestelder** [comment]
Do you have steps to reproduce this? Not really a big deal for this issue but I am curious how you managed to do that because I've been trying locally and can't get it to happen.

**Comment by ethanpartida** [comment]
Yes, try inputting 3-2 for the range of inputs. Both boxes will go red. Then change the 1-3 and submit. Only the 1 will change colors not the two. (The two changes if you edit it at all though)

On Nov 5, 2019 3:30 PM, theeldestelder <notifications@github.com> wrote:

Do you have steps to reproduce this? Not really a big deal for this issue but I am curious how you managed to do that because I've been trying locally and can't get it to happen.

**Comment by theeldestelder** [comment]
Closed by #125
