### ISSUE TITLE
DMX - Integrate DMX

### ISSUE THREAD

**Issue by ByronAmbright** [teslaworksumn/lightshow-Gallium#13]
Using open source software or our own implementation we need to be able to interact with our usb to dmx controllers. We should autodetect the usb port that the dmx is in, or in the case of more than one pick the one that was put in last. There should be a option in the settings to manually pick which one you want to use.

**Comment by theeldestelder** [comment]
[One way to get permission to write to ttyUSB* on Linux](https://askubuntu.com/questions/112568/how-do-i-allow-a-non-default-user-to-use-serial-device-ttyusb0/112572#112572)
[NPM DMX library](https://github.com/wiedi/node-dmx)
