### ISSUE TITLE
Server to host binaries of finished app

### ISSUE THREAD

**Issue by ByronAmbright** [teslaworksumn/lightshow-Gallium#9]
Setup a server that stores all the binaries of each version of the app. The server will also have a html page that will give you a link to the most current version of the app. Either we detect the platform the user is on and give the user only that link or we just given them all the links for every platform. Every time something is merged into master, new binaries should be made and uploaded to this server. The README should be updated to mention how to this html page and also how to download previous versions of the app.  A basecamp post should be made about this as well as putting this into the wiki.

**Comment by nickschatz** [comment]
Are nightly builds necessary? Will we be developing up to the minute of the light show?

If not, can we just publish in Releases on Github?

If so, how about continuous integration so we get a binary for every commit to master?

**Comment by theeldestelder** [comment]
Nightly builds probably aren't necessary.  And I think you'd be surprised at how late some things have come together the past couple years for light show.  We've been trying to make sure that doesn't happen for at least as long as I've been around, but there's always some sort of scramble at the end with respect to one part of the show or another.

Publishing in releases is a great idea.  Also having a CI to publish a separate binary for every commit to master is another good idea.
